#!/bin/bash

function curse-bukkit {
  get-file "http://mods.curse.com/bukkit-plugins/minecraft/$1/download" "$2.html"
  funcret="$?"
  if [[ "$funcret" != "0" ]]; then
    return "$funcret"
  fi
  funcurl="$(grep "data-href=" "$2.html" | sed 's/^.*data-href="\([^"]*\)".*$/\1/' | head -n 1)"
  if [[ "$funcurl" == "" ]]; then
    return 2
  fi
  get-file "$funcurl" "$2"
  return "$?"
}

if [ "${0##*/}" == "curse-bukkit" ]; then
  curse-bukkit "$@"
  exit "$?"
fi
