#!/bin/bash

function curse-bukkit {
  if [ -f "$2.html" ]; then
    curl "http://mods.curse.com/bukkit-plugins/minecraft/$1/download" -z "$2.html" -o "$2.html" --silent --location
    funcret="$?"
  else
    curl "http://mods.curse.com/bukkit-plugins/minecraft/$1/download" -o "$2.html" --silent --location
    funcret="$?"
  fi
  if [[ "$funcret" != "0" ]]; then
    return "$funcret"
  fi
  funcurl="$(grep "data-href=" "$2.html" | sed 's/^.*data-href="\([^"]*\)".*$/\1/' | head -n 1)"
  if [[ "$funcurl" == "" ]]; then
    return 2
  fi
  if [ -f "$2" ]; then
    curl "$funcurl" -z "$2" -o "$2" --silent --location
    return "$?"
  else
    curl "$funcurl" -o "$2" --silent --location
    return "$?"
  fi
}

if [ "${0##*/}" == "curse-bukkit" ]; then
  curse-bukkit "$@"
  exit "$?"
fi
