#!/bin/bash

function mcpluginmeta {
  local f="$1"
  if [ ! -f "$f" ]; then
    local fen="$MINECRAFTDIR/plugins/.$1.mc_plugin"
    if [ -f "$fen" ]; then
      local f="$fen"
    else
      echo "mcpluginmeta: installed plugin '$1' not found." >&2
      return 8
    fi
  fi
  ret=64
  if [[ "$2" == "" ]]; then
    cat "$f"
    ret=$?
  else
    grep "^\"$2\":" "$f" | sed 's/.*": *//' | sed 's/^ *"\(.*\)" *,\{0,1\} *$/\1/'
    ret=$?
  fi
  return $ret
}

function mcpluginsetmetastr {
  local f="$1"
  if [ ! -f "$f" ]; then
    local fen="$MINECRAFTDIR/plugins/.$1.mc_plugin"
    if [ -f "$fen" ]; then
      local f="$fen"
    else
      echo "mcpluginmeta: installed plugin '$1' not found." >&2
      return 8
    fi
  fi
  sed -i 's|^"'"$2"'": *".*" *\(,\{0,1\}\) *$|"'"$2"'": "'"$3"'"\1|' "$f"
}

function mcpluginsetmetanum {
  local f="$1"
  if [ ! -f "$f" ]; then
    local fen="$MINECRAFTDIR/plugins/.$1.mc_plugin"
    if [ -f "$fen" ]; then
      local f="$fen"
    else
      echo "mcpluginmeta: installed plugin '$1' not found." >&2
      return 8
    fi
  fi
  sed -i 's/^"'"$2"'":[^,]*\(,\{0,1\}\) *$/"'"$2"'": '"$3"'\1/' "$f"
}
